# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Apricis
email: dkalpackchi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A personal blog of Dmytro Kalpakchi with posts on different topics and experiments with data.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
facebook_username: dmytro.kalpakchi
github_username:  apricis

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima
gems:
  - jekyll-feed
  - jemoji
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  tag:
    output: true
    permalink: /:path/
  category:
    output: true
    permalink: /:path/


permalink: pretty

# direct translation
default_lang: 'en'
languages: ['en', 'uk']
i18n:
  en:
    posts:
      posted_at: posted at
      in_category: in category
      tagged_by: tagged by
    menu:
      posts: Posts
      sandbox: Scientific sandbox
      projects: Social projects
      about: About me
      lang: In English
    categories:
      thoughts: thoughts
      en: In English
    tags:
      welcome: welcome
      hello: hello
    dates:
      Jan: Jan
      Feb: Feb
      Mar: Mar
      Apr: Apr
      May: May
      Jun: Jun
      Jul: Jul
      Aug: Aug
      Sep: Sep
      Oct: Oct
      Nov: Nov
      Dec: Dec
  uk:
    posts:
      posted_at: опубліковано
      in_category: у категорії
      tagged_by: із позначками
    menu:
      posts: Дописи
      sandbox: Наукова пісочниця
      projects: Соціальні проекти
      about: Про мене
      lang: Українською
    categories:
      thoughts: роздуми
      uk: Українською
    tags:
      welcome: вітання
      hello: привіт
    dates:
      Jan: Січ
      Feb: Лют
      Mar: Бер
      Apr: Кві
      May: Тра
      Jun: Чер
      Jul: Лип
      Aug: Серп
      Sep: Вер
      Oct: Жов
      Nov: Лис
      Dec: Гру
